=begin
#Capture the Flag

#A friendly game of Capture the Flag

The version of the OpenAPI document: 1.0.0
Contact: hello@testdouble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GameClient::InlineResponse400
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InlineResponse400' do
  before do
    # run before each test
    @instance = GameClient::InlineResponse400.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse400' do
    it 'should create an instance of InlineResponse400' do
      expect(@instance).to be_instance_of(GameClient::InlineResponse400)
    end
  end
  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
