=begin
#Capture the Flag

#A friendly game of Capture the Flag

The version of the OpenAPI document: 1.0.0
Contact: hello@testdouble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'game-client/api_client'
require 'game-client/api_error'
require 'game-client/version'
require 'game-client/configuration'

# Models
require 'game-client/models/error'
require 'game-client/models/flag'
require 'game-client/models/inline_response202'
require 'game-client/models/inline_response400'
require 'game-client/models/player'

# APIs
require 'game-client/api/game_api'

module GameClient
  class << self
    # Customize default settings for the SDK using block.
    #   GameClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
