# -*- encoding: utf-8 -*-

=begin
#Capture the Flag

#A friendly game of Capture the Flag

The version of the OpenAPI document: 1.0.0
Contact: hello@testdouble.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "game-client/version"

Gem::Specification.new do |s|
  s.name        = "game-client"
  s.version     = GameClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["hello@testdouble.com"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Capture the Flag Ruby Gem"
  s.description = "Client library of GameAPI"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
