/**
 * Capture the Flag
 * A friendly game of Capture the Flag
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@testdouble.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GameClient);
  }
}(this, function(expect, GameClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GameClient.Flag();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Flag', function() {
    it('should create an instance of Flag', function() {
      // uncomment below and update the code to test Flag
      //var instane = new GameClient.Flag();
      //expect(instance).to.be.a(GameClient.Flag);
    });

    it('should have the property revealed (base name: "revealed")', function() {
      // uncomment below and update the code to test the property revealed
      //var instane = new GameClient.Flag();
      //expect(instance).to.be();
    });

    it('should have the property held (base name: "held")', function() {
      // uncomment below and update the code to test the property held
      //var instane = new GameClient.Flag();
      //expect(instance).to.be();
    });

    it('should have the property x (base name: "x")', function() {
      // uncomment below and update the code to test the property x
      //var instane = new GameClient.Flag();
      //expect(instance).to.be();
    });

    it('should have the property y (base name: "y")', function() {
      // uncomment below and update the code to test the property y
      //var instane = new GameClient.Flag();
      //expect(instance).to.be();
    });

  });

}));
