/**
 * Capture the Flag
 * A friendly game of Capture the Flag
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@testdouble.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Flag model module.
 * @module model/Flag
 * @version 1.0.0
 */
class Flag {
    /**
     * Constructs a new <code>Flag</code>.
     * Opponent flag information
     * @alias module:model/Flag
     * @param revealed {Boolean} 
     * @param held {Boolean} 
     * @param x {Number} 
     * @param y {Number} 
     */
    constructor(revealed, held, x, y) { 
        
        Flag.initialize(this, revealed, held, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, revealed, held, x, y) { 
        obj['revealed'] = revealed;
        obj['held'] = held;
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>Flag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Flag} obj Optional instance to populate.
     * @return {module:model/Flag} The populated <code>Flag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Flag();

            if (data.hasOwnProperty('revealed')) {
                obj['revealed'] = ApiClient.convertToType(data['revealed'], 'Boolean');
            }
            if (data.hasOwnProperty('held')) {
                obj['held'] = ApiClient.convertToType(data['held'], 'Boolean');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} revealed
 */
Flag.prototype['revealed'] = undefined;

/**
 * @member {Boolean} held
 */
Flag.prototype['held'] = undefined;

/**
 * @member {Number} x
 */
Flag.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
Flag.prototype['y'] = undefined;






export default Flag;

