/**
 * Capture the Flag
 * A friendly game of Capture the Flag
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@testdouble.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Flag from './Flag';
import Player from './Player';

/**
 * The InlineResponse202 model module.
 * @module model/InlineResponse202
 * @version 1.0.0
 */
class InlineResponse202 {
    /**
     * Constructs a new <code>InlineResponse202</code>.
     * @alias module:model/InlineResponse202
     */
    constructor() { 
        
        InlineResponse202.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse202</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse202} obj Optional instance to populate.
     * @return {module:model/InlineResponse202} The populated <code>InlineResponse202</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse202();

            if (data.hasOwnProperty('player')) {
                obj['player'] = Player.constructFromObject(data['player']);
            }
            if (data.hasOwnProperty('flag')) {
                obj['flag'] = Flag.constructFromObject(data['flag']);
            }
            if (data.hasOwnProperty('opponents')) {
                obj['opponents'] = ApiClient.convertToType(data['opponents'], [Player]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Player} player
 */
InlineResponse202.prototype['player'] = undefined;

/**
 * @member {module:model/Flag} flag
 */
InlineResponse202.prototype['flag'] = undefined;

/**
 * @member {Array.<module:model/Player>} opponents
 */
InlineResponse202.prototype['opponents'] = undefined;






export default InlineResponse202;

