/**
 * Capture the Flag
 * A friendly game of Capture the Flag
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@testdouble.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Player model module.
 * @module model/Player
 * @version 1.0.0
 */
class Player {
    /**
     * Constructs a new <code>Player</code>.
     * Player information
     * @alias module:model/Player
     * @param hasPeg {Boolean} 
     * @param hasFlag {Boolean} 
     * @param isInSafeZone {Boolean} 
     * @param x {Number} 
     * @param y {Number} 
     */
    constructor(hasPeg, hasFlag, isInSafeZone, x, y) { 
        
        Player.initialize(this, hasPeg, hasFlag, isInSafeZone, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hasPeg, hasFlag, isInSafeZone, x, y) { 
        obj['has_peg'] = hasPeg;
        obj['has_flag'] = hasFlag;
        obj['is_in_safe_zone'] = isInSafeZone;
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>Player</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Player} obj Optional instance to populate.
     * @return {module:model/Player} The populated <code>Player</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Player();

            if (data.hasOwnProperty('has_peg')) {
                obj['has_peg'] = ApiClient.convertToType(data['has_peg'], 'Boolean');
            }
            if (data.hasOwnProperty('has_flag')) {
                obj['has_flag'] = ApiClient.convertToType(data['has_flag'], 'Boolean');
            }
            if (data.hasOwnProperty('is_in_safe_zone')) {
                obj['is_in_safe_zone'] = ApiClient.convertToType(data['is_in_safe_zone'], 'Boolean');
            }
            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} has_peg
 */
Player.prototype['has_peg'] = undefined;

/**
 * @member {Boolean} has_flag
 */
Player.prototype['has_flag'] = undefined;

/**
 * @member {Boolean} is_in_safe_zone
 */
Player.prototype['is_in_safe_zone'] = undefined;

/**
 * @member {Number} x
 */
Player.prototype['x'] = undefined;

/**
 * @member {Number} y
 */
Player.prototype['y'] = undefined;






export default Player;

