'!include': ../config.yml
additionalProperties:
  moduleName: GameClient
  projectDescription: Client library of GameAPI
  projectName: game-client
  usePromises: true
generatorName: javascript
outputDir: ../capture-the-flag-client-js/
