'!include': ../config.yml
additionalProperties:
  gemDescription: Client library of GameAPI
  gemName: game-client
  moduleName: GameClient
generatorName: ruby
outputDir: ../capture-the-flag-client-rb/
